version: "3"
services:
  nuxt:
    build: ./frontend/
    container_name: mongo-exporter
    restart: always
    ports:
      - "8080:8080"
    command: "npm run serve"
    depends_on:
      - backend
  backend:
    build: ./backend/
    container_name: mongo-exporter-backend
    restart: always
    ports:
      - "3000:3000"
      - "27017:27017"
